const events = [
  {
    name: "Concierto de Rock en Lima",
    description:
      "Disfruta de una noche de rock con las mejores bandas locales.",
    category: "Música",
    date: "2024-07-10",
    time: "20:00",
    address: "Estadio Nacional, Lima",
    latitude: -12.0453,
    longitude: -77.0311,
  },
  {
    name: "Feria del Libro de Cusco",
    description:
      "Un evento para los amantes de la lectura con autores invitados.",
    category: "Literatura",
    date: "2024-07-12",
    time: "10:00",
    address: "Plaza de Armas, Cusco",
    latitude: -13.5162,
    longitude: -71.9782,
  },
  {
    name: "Seminario de Negocios en Arequipa",
    description:
      "Conferencia sobre las nuevas tendencias en el mundo empresarial.",
    category: "Negocios",
    date: "2024-07-15",
    time: "09:00",
    address: "Centro de Convenciones Cerro Juli, Arequipa",
    latitude: -16.3989,
    longitude: -71.5369,
  },
  {
    name: "Festival de Cine en Trujillo",
    description: "Muestra de cine independiente con proyecciones y charlas.",
    category: "Cine",
    date: "2024-07-20",
    time: "18:00",
    address: "Teatro Municipal, Trujillo",
    latitude: -8.109,
    longitude: -79.0215,
  },
  {
    name: "Exposición de Arte Contemporáneo en Lima",
    description: "Galería con las últimas obras de artistas contemporáneos.",
    category: "Arte",
    date: "2024-07-25",
    time: "14:00",
    address: "Museo de Arte de Lima, Lima",
    latitude: -12.0586,
    longitude: -77.0365,
  },
  {
    name: "Taller de Cocina Peruana en Cusco",
    description:
      "Aprende a preparar los platos típicos de la gastronomía peruana.",
    category: "Gastronomía",
    date: "2024-07-30",
    time: "16:00",
    address: "Centro Gastronómico, Cusco",
    latitude: -13.5202,
    longitude: -71.975,
  },
  {
    name: "Concierto de Música Clásica en Arequipa",
    description:
      "Una noche de música clásica con la orquesta sinfónica de Arequipa.",
    category: "Música",
    date: "2024-08-05",
    time: "19:00",
    address: "Teatro Municipal, Arequipa",
    latitude: -16.409,
    longitude: -71.5368,
  },
  {
    name: "Conferencia de Tecnología en Lima",
    description: "Encuentro de expertos en tecnología y nuevas tendencias.",
    category: "Tecnología",
    date: "2024-08-10",
    time: "09:00",
    address: "Centro de Convenciones, Lima",
    latitude: -12.0432,
    longitude: -77.0282,
  },
  {
    name: "Festival de Danza Folklórica en Cusco",
    description:
      "Muestra de danzas tradicionales de todas las regiones de Perú.",
    category: "Cultura",
    date: "2024-08-15",
    time: "17:00",
    address: "Plaza de Armas, Cusco",
    latitude: -13.5162,
    longitude: -71.9782,
  },
  {
    name: "Feria Gastronómica en Trujillo",
    description: "Disfruta de los mejores platos de la cocina peruana.",
    category: "Gastronomía",
    date: "2024-08-20",
    time: "12:00",
    address: "Parque Principal, Trujillo",
    latitude: -8.1112,
    longitude: -79.0284,
  },
  {
    name: "Exposición de Fotografía en Lima",
    description: "Galería de fotografías de reconocidos artistas nacionales.",
    category: "Fotografía",
    date: "2024-08-25",
    time: "15:00",
    address: "Centro Cultural, Lima",
    latitude: -12.0621,
    longitude: -77.0375,
  },
  {
    name: "Torneo de Ajedrez en Arequipa",
    description: "Competencia abierta para ajedrecistas de todas las edades.",
    category: "Deportes",
    date: "2024-08-30",
    time: "10:00",
    address: "Club de Ajedrez, Arequipa",
    latitude: -16.3989,
    longitude: -71.5369,
  },
  {
    name: "Festival de Jazz en Lima",
    description:
      "Disfruta de una noche de jazz con bandas locales e internacionales.",
    category: "Música",
    date: "2024-09-05",
    time: "20:00",
    address: "Anfiteatro del Parque de la Exposición, Lima",
    latitude: -12.0656,
    longitude: -77.0337,
  },
  {
    name: "Conferencia de Marketing Digital en Cusco",
    description: "Aprende las últimas estrategias de marketing digital.",
    category: "Negocios",
    date: "2024-09-10",
    time: "09:00",
    address: "Centro de Convenciones, Cusco",
    latitude: -13.516,
    longitude: -71.9783,
  },
  {
    name: "Feria de Ciencias en Arequipa",
    description:
      "Exposición de proyectos científicos de estudiantes y profesionales.",
    category: "Ciencia",
    date: "2024-09-15",
    time: "10:00",
    address: "Universidad Nacional de San Agustín, Arequipa",
    latitude: -16.4065,
    longitude: -71.5374,
  },
  {
    name: "Taller de Pintura en Trujillo",
    description: "Aprende técnicas de pintura con artistas locales.",
    category: "Arte",
    date: "2024-09-20",
    time: "14:00",
    address: "Centro de Arte, Trujillo",
    latitude: -8.1104,
    longitude: -79.0301,
  },
  {
    name: "Feria de Empleo en Lima",
    description: "Encuentra oportunidades laborales en diversas industrias.",
    category: "Negocios",
    date: "2024-09-25",
    time: "09:00",
    address: "Centro de Convenciones, Lima",
    latitude: -12.0453,
    longitude: -77.0311,
  },
  {
    name: "Concierto de Música Andina en Cusco",
    description:
      "Disfruta de la música tradicional andina con reconocidos artistas.",
    category: "Música",
    date: "2024-09-30",
    time: "19:00",
    address: "Teatro Municipal, Cusco",
    latitude: -13.5159,
    longitude: -71.9792,
  },
  {
    name: "Festival de Comida Vegana en Arequipa",
    description:
      "Prueba una variedad de platos veganos y aprende sobre la alimentación saludable.",
    category: "Gastronomía",
    date: "2024-10-05",
    time: "12:00",
    address: "Parque Selva Alegre, Arequipa",
    latitude: -16.4054,
    longitude: -71.5373,
  },
  {
    name: "Torneo de Fútbol en Trujillo",
    description: "Competencia abierta para equipos de todas las edades.",
    category: "Deportes",
    date: "2024-10-10",
    time: "08:00",
    address: "Estadio Mansiche, Trujillo",
    latitude: -8.1091,
    longitude: -79.0216,
  },
];

export default events;